version: "3"
services:
  whisper-ui:
    container_name: whisper-ui
    image: whisper-ui
    build:
      context: whisper-ui
      dockerfile: Dockerfile

  whisper-proxy:
    container_name: whisper-proxy
    image: nginx:1.20.2-alpine
    restart: unless-stopped
    volumes:
      - "./proxy/nginx.conf:/etc/nginx/nginx.conf"
    stop_grace_period: 30s
    ports:
      - "8080:8080"

  whisper-api:
    container_name: whisper-api
    image: whisper-api
    build:
      context: whisper-api
      dockerfile: Dockerfile
    volumes:
      - "/Users/adavila/Documents/andres/github/whisper/whisper-api/models/:/home/python/models"
    environment:
      OMP_NUM_THREADS: 1
    ports:
      - "5000:5000"
